# Generated by Django 4.2.1 on 2023-05-25 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_alter_award_award_alter_award_commands_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='marr',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='subscribes',
            new_name='subscribe',
        ),
        migrations.RemoveField(
            model_name='award',
            name='commands',
        ),
        migrations.RemoveField(
            model_name='command',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='command',
            name='invites',
        ),
        migrations.RemoveField(
            model_name='command',
            name='review',
        ),
        migrations.RemoveField(
            model_name='command',
            name='solutions',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='commands',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='number',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='users',
        ),
        migrations.RemoveField(
            model_name='task',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
        migrations.AddField(
            model_name='award',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_awards', to='gateway.command'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='gateway.tag'),
        ),
        migrations.AlterField(
            model_name='award',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_awards', to='gateway.task'),
        ),
        migrations.AlterField(
            model_name='command',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contest_commands', to='gateway.contest'),
        ),
        migrations.RemoveField(
            model_name='command',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='command',
            name='tags',
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contests_admin', to=settings.AUTH_USER_MODEL, verbose_name='contest_admins'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.RemoveField(
            model_name='contest',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='tags',
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('CRE', 'CREATED'), ('ACC', 'ACCEPTED'), ('REJ', 'REJECTED')], max_length=3),
        ),
        migrations.AlterField(
            model_name='solution',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solution_to_command', to='gateway.command'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('CRE', 'CREATED'), ('REV', 'REVIEWED'), ('BAN', 'BANNED')], max_length=3),
        ),
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solution_to_task', to='gateway.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contest_tasks', to='gateway.contest'),
        ),
        migrations.AddField(
            model_name='command',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='command',
            name='tags',
            field=models.ManyToManyField(to='gateway.tag'),
        ),
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='contests_participant', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
        migrations.AddField(
            model_name='contest',
            name='tags',
            field=models.ManyToManyField(to='gateway.tag'),
        ),
    ]
