# Generated by Django 4.2.1 on 2023-05-25 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_remove_contest_contest_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_commands', to=settings.AUTH_USER_MODEL),
        ),
    ]
