# Generated by Django 4.2.1 on 2023-05-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_command_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_commands', to='gateway.task'),
        ),
    ]
