# Generated by Django 4.2.1 on 2023-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_command_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='logo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='gateway.tag'),
        ),
    ]
