# Generated by Django 4.2.1 on 2023-05-27 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0010_alter_contest_logo_alter_contest_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_commands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='command',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contest_commands', to='gateway.contest'),
        ),
    ]
