# Generated by Django 4.2.1 on 2023-06-01 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0011_alter_command_admin_alter_command_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviter_to_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
