# Generated by Django 4.2.1 on 2023-06-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0012_alter_invite_inviter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
