# Generated by Django 4.2.1 on 2023-06-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0013_alter_contest_logo_alter_task_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='logo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
